# Generated by Django 2.2 on 2019-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('idbanco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ci', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('deudor', models.TextField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('idcorreo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'correos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetBancos',
            fields=[
                ('tipo_cuenta', models.CharField(blank=True, max_length=1, null=True)),
                ('n_cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('n_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_seg', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_internet', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_internet', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_cajero', models.SmallIntegerField(blank=True, null=True)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_especial', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'det_bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCorreos',
            fields=[
                ('iddetcorreos', models.AutoField(primary_key=True, serialize=False)),
                ('ususario', models.CharField(blank=True, max_length=20, null=True)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('tlf_correo', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_rec', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'det_correos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetFact',
            fields=[
                ('iddetfact', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('detalles', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'det_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('num_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fact', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetPago',
            fields=[
                ('id_met', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=1)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'met_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(blank=True, max_length=40, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tipos_productos',
                'managed': False,
            },
        ),
    ]
