# Generated by Django 2.2 on 2019-07-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bancos',
        ),
        migrations.DeleteModel(
            name='Correos',
        ),
        migrations.RemoveField(
            model_name='detbancos',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='detcorreos',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='detfact',
            name='num_factura',
        ),
        migrations.RemoveField(
            model_name='metpago',
            name='num_factura',
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='TiposProductos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='DetBancos',
        ),
        migrations.DeleteModel(
            name='DetCorreos',
        ),
        migrations.DeleteModel(
            name='DetFact',
        ),
        migrations.DeleteModel(
            name='Facturas',
        ),
        migrations.DeleteModel(
            name='MetPago',
        ),
    ]
