# Generated by Django 2.2 on 2019-07-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appmain', '0002_auto_20190704_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('idbanco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ci', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('deudor', models.TextField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('idcorreo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'correos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('num_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_fact', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('n_cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(blank=True, max_length=40, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tipos_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetBancos',
            fields=[
                ('ci', models.ForeignKey(db_column='ci', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appmain.Clientes')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=1, null=True)),
                ('n_cuenta', models.CharField(max_length=20)),
                ('n_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('cod_seg', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_internet', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_internet', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_cajero', models.SmallIntegerField(blank=True, null=True)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_especial', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'det_bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetCorreos',
            fields=[
                ('ci', models.ForeignKey(db_column='ci', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appmain.Clientes')),
                ('ususario', models.CharField(blank=True, max_length=20, null=True)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('tlf_correo', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_rec', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'det_correos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetFact',
            fields=[
                ('num_factura', models.ForeignKey(db_column='num_factura', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appmain.Facturas')),
                ('cantidad', models.SmallIntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('detalles', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'det_fact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetPago',
            fields=[
                ('num_factura', models.ForeignKey(db_column='num_factura', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appmain.Facturas')),
                ('tipo_pago', models.CharField(max_length=1)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'met_pago',
                'managed': False,
            },
        ),
    ]
